server:
  port: 8084

spring:
  application:
    name: fluxion-worker-demo

# Worker 配置（生产环境）
fluxion:
  worker:
    brokers:
      - http://localhost:9785
    port: 9787
    queue-size: 64
    tags:
      - env=prod
      - version=1.0

# 日志配置
logging:
  config: classpath:log4j2.xml
