spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:./fluxion;DB_CLOSE_DELAY=-1;MODE=mysql;
  # h2
  h2:
    # h2嵌入式数据库控制台，可以通过浏览器访问 ip:port/h2-console
    # file 模式 用户名密码都是空
    # mem 模式 用户名 sa 密码空
    console:
      path: /h2-console
      enabled: true
      #      settings:
      # rootrootroot
  #        web-admin-password: b218ada98873d7ce73d170600ba5bdcd2dd2379e4ba2e84d2bcfa42bb1efd97e0d21f1406650bade15c3f9e06d5b8e2a4fa79a616db52ab31ce49e862127ea75